version: '3'
services:
  mysql:
    container_name: MDO-Database
    #     platform: linux/x86_64
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - /root/mdo-source/mdo-nuxt/server/data:/var/lib/mysql
      # - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MDO-DB-Password
      MYSQL_DATABASE: mdo-database
      MYSQL_USER: MDO-DB-Admin
      MYSQL_PASSWORD: MDO-DB-Password
  strapi:
    build: .
    container_name: MDO-Api
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: mdo-database
      DATABASE_USERNAME: MDO-DB-Admin
      DATABASE_PASSWORD: MDO-DB-Password
      DATABASE_SSL: 'false'
      APP_KEYS: V3a8bqYkjr1IOG6pkjwuBA==,Pv5xg/4cUFjL3X1YAMo3Hg==,GrwU7AelWGPmfY1cwl7znQ==,0qTeOMaudnBr/h/NFJWdSg==
      JWT_SECRET: 0858f0f9-9e7f-4299-a4dd-3a087812042a
      API_TOKEN_SALT: 66bd9ad81641e2131b6f241716739f36
      CLOUDINARY_NAME: bsd-assets
      CLOUDINARY_KEY: 412128275792396
      CLOUDINARY_SECRET: fobh4dGwCpAxvaZuOq9D-0MYao0
    ports:
      - '1337:1337'
    depends_on:
      - mysql
